### ISSUE TITLE
check_snmp_int.pl stop working

### ISSUE THREAD

**Issue by zijam** [dnsmichi/manubulon-snmp#11]
When I run this command on my machine, I get following error:
```
root@efomf:/usr/lib/nagios/plugins# ./check_snmp_int.pl -H 192.168.200.1 -C abcdefg -s -n Eth*
usage: $sock->socket(DOMAIN, TYPE, PROTOCOL) at /usr/share/perl5/Net/SNMP/Transport/IPv4.pm line 36
```

Running in a docker container 'google/debian:wheezy'
Debian version 7.8
Linux efomf.dk 2.6.32-504.12.2.el6.x86_64 #1 SMP Wed Mar 11 22:03:14 UTC 2015 x86_64 GNU/Linux

**Comment by Ilya33** [comment]
Hello, zijam.
You MUST have /etc/protocol file in you docker

**Comment by zijam** [comment]
ok.. will try to check if it solve the problem.

**Comment by zijam** [comment]
After installing libnet-perl it works
