### ISSUE TITLE
check_snmp_load.pl NetScreen OID's wrong?

### ISSUE THREAD

**Issue by phospi** [dnsmichi/manubulon-snmp#13]
Hi,

the documentation of Juniper has a different description as the github script as you can see here:
http://kb.juniper.net/InfoCenter/index?page=content&id=KB25797&actp=search

Juniper:
    .1.3.6.1.4.1.3224.16.1.1.0 Average System CPU utilization in percentage.
    .1.3.6.1.4.1.3224.16.1.2.0 Last one minute CPU utilization in percentage.
    .1.3.6.1.4.1.3224.16.1.3.0 Last Five minute CPU utilization in percentage.
    .1.3.6.1.4.1.3224.16.1.4.0 Last Fifteen minute CPU utilization in percentage.

Script:
my $nsc_cpu_5m = "1.3.6.1.4.1.3224.16.1.4.0"; # NS CPU load (5min %)
my $nsc_cpu_1m = "1.3.6.1.4.1.3224.16.1.2.0"; # NS CPU load (1min %)
my $nsc_cpu_5s = "1.3.6.1.4.1.3224.16.1.3.0"; # NS CPU load (5sec %) 

The documentation of Juniper dates back to 2012. I can't tell if juniper changed something or not....

**Comment by dnsmichi** [comment]
I don't have access to such hardware so there may be two options for you as alternative: 1) ask at monitoring-portal.org how others solved it 2) look for similar scripts and their oids.

**Comment by phospi** [comment]
Thanks for your replay, but what?
I have limited access to such hardware. Definitely not enough for a significant test. Easiest for me is downloading and altering the script. I don't need to look for similar scripts. Only the vendors' MIB file will give a definite answer. I will give an update when i've found something useful.

There may be others who download check_snmp_load.pl since this is a public repository. Those others might be unaware that the script doesn't deliver correct Juniper load results. 

I know this repository is not the original one but as far as I can see is that changes have been made to the scripts. I am not very familiar with github. It seems to me the best option to step forward and raise an issue.

**Comment by dnsmichi** [comment]
I tried to express that I cannot help you here, and tried to suggest possible ways to get help with your problem. If you find a patch, or anything else helping resolve the issue, I'll merge it upstream. If you want to step up as maintainer, I'll also grant you commit access to this repository :)

**Comment by phospi** [comment]
Wow :)
Well, I have no experience in committing code. I don't want break something or do foolish. I try to get more details to the issue and will suggest a code change.

**Comment by dnsmichi** [comment]
Any updates from your research?
