### ISSUE TITLE
Apply a programming style to the plugins

### ISSUE THREAD

**Issue by foobar0815** [dnsmichi/manubulon-snmp#20]
Hej,

this isn't exactly an issue/bug...

Programming style of the plugins is pretty random right now (indention, line length, placement of parentheses, brackets, etc.). This makes it difficult to contribute even small changes or bugfixes to the project.

I propose reformatting the plugins with [Perltidy](http://perltidy.sourceforge.net) and placing the initially used options in a .perltidyrc in the plugins-directory. Potential contributors would only have to run perltidy again to make sure any changes comply with the standard.

Feel free to close this issue if you don't agree.

**Comment by dnsmichi** [comment]
I don't like the current style either, but finding the correct one is rather hard. I have no objections against a clear proposal including a patch already (but I won't have the time to look into that myself).
