### ISSUE TITLE
check_snmp_process.pl does not honour timeout (-t)

### ISSUE THREAD

**Issue by gibsonc** [dnsmichi/manubulon-snmp#21]
$TIMEOUT is statically defined as 15s.
The else at line 338 will never execute with the -t value ($o_timeout)

Since $o_timeout is defined as 5s by default in Globals I guess one could remove $TIMEOUT and just replace the block with

if (defined($o_timeout)) {
   verb("Alarm at $o_timeout");
   alarm($o_timeout);
}

**Comment by dnsmichi** [comment]
That is the case for all plugins - do you have a patch? :)

**Comment by dnsmichi** [comment]
Obviously not. I've analyzed the existing source code a bit, and probably this comes from the previous "utils.pm" change where one could define the $TIMEOUT variable in a global fashion. This doesn't exist anymore.

Furthermore the plugin output on timeouts isn't really nice and often alarm handlers aren't installed. This now looks like this:

````
michi@imagine ~/coding/github/manubulon-snmp/plugins (master) $ perl check_snmp_process.pl -H 192.168.33.1 -C public -2 -n httpd -t 2
No answer from host 192.168.33.1:161
````
