### ISSUE TITLE
Cisco SMB switch

### ISSUE THREAD

**Issue by spali** [dnsmichi/manubulon-snmp#30]
Cisco SMB switches seams to use different OID's.
At least I tested it with my SG500, by overwriting the cisco values:
```
my $cisco_cpu_5m = "1.3.6.1.4.1.9.6.1.101.1.9.0";      # Cisco CPU load (5min %)
my $cisco_cpu_1m = "1.3.6.1.4.1.9.6.1.101.1.8.0";      # Cisco CPU load (1min %)
my $cisco_cpu_5s = "1.3.6.1.4.1.9.6.1.101.1.7.0";      # Cisco CPU load (5sec %)
```
Output for the plugin: `CPU : 5 3 3 : OK`
Source: https://supportforums.cisco.com/discussion/12195886/sg-500-snmp-oid-cpu-load

Just in case you want to include this as an additional type

**Comment by dnsmichi** [comment]
Thanks, I do not have any hardware to test on. So I'd appreciate if you could add that type by yourself and send in a PR :)

**Comment by spali** [comment]
here we go
