### ISSUE TITLE
Data Not Fully Defined - UNKNOWN

### ISSUE THREAD

**Issue by flippym** [dnsmichi/manubulon-snmp#33]
The plugin **check_snmp_storage.pl** is currently returning a UNKNWON error. The SNMP communication seems fine and he seem to be implying the difficulty is in the new `pam_systemd` user running environment.

It has been working fine with RHEL6, but recently installed a new server with RHEL7 which is returning this error.

> [username@localhost ~]$ /usr/bin/perl check_snmp_storage.pl -H servertocheck -C communitystring -2 -p 161  -w 85 -c 90  -f -q FixedDisk -G -f '' -e -m '/dev|/otherpath'
> Use of uninitialized value in concatenation (.) or string at test line 659.
> Use of uninitialized value in concatenation (.) or string at test line 660.
> Use of uninitialized value in concatenation (.) or string at test line 661.
> Data not fully defined for storage /run/user/66236 : UNKNOWN

**Comment by flippym** [comment]
Although passing the -o argument with some value greater than the predefined works. The missing data maybe triggering this error.

**Comment by dnsmichi** [comment]
Can you run the script more verbose with `-v` and post the output please?

**Comment by flippym** [comment]
Alarm at 15
SNMP v2c login
Filter : /dev|/otherpath
OID : 1.3.6.1.2.1.25.2.3.1.3.72, Desc : /run/user/1763
   OID : 1.3.6.1.2.1.25.2.3.1.2.72, Storagetype: FixedDisk ?= FixedDisk
   Name : /run/user/1763, Index : 72
OID : 1.3.6.1.2.1.25.2.3.1.3.86, Desc : /run/user/1923
   OID : 1.3.6.1.2.1.25.2.3.1.2.86, Storagetype: FixedDisk ?= FixedDisk
   Name : /run/user/1923, Index : 86
OID : 1.3.6.1.2.1.25.2.3.1.3.81, Desc : /run/user/1075
   OID : 1.3.6.1.2.1.25.2.3.1.2.81, Storagetype: FixedDisk ?= FixedDisk
   Name : /run/user/1075, Index : 81
OID : 1.3.6.1.2.1.25.2.3.1.3.63, Desc : /backups
   OID : 1.3.6.1.2.1.25.2.3.1.2.63, Storagetype: FixedDisk ?= FixedDisk
   Name : /backups, Index : 63
OID : 1.3.6.1.2.1.25.2.3.1.3.87, Desc : /run/user/2517
   OID : 1.3.6.1.2.1.25.2.3.1.2.87, Storagetype: FixedDisk ?= FixedDisk
   Name : /run/user/2517, Index : 87
OID : 1.3.6.1.2.1.25.2.3.1.3.6, Desc : Memory buffers
   OID : 1.3.6.1.2.1.25.2.3.1.2.6, Storagetype: Other ?= FixedDisk
OID : 1.3.6.1.2.1.25.2.3.1.3.167, Desc : /run/user/1243
   OID : 1.3.6.1.2.1.25.2.3.1.2.167, Storagetype: FixedDisk ?= FixedDisk
   Name : /run/user/1243, Index : 167
OID : 1.3.6.1.2.1.25.2.3.1.3.160, Desc : /run/user/2867
   OID : 1.3.6.1.2.1.25.2.3.1.2.160, Storagetype: FixedDisk ?= FixedDisk
   Name : /run/user/2867, Index : 160
OID : 1.3.6.1.2.1.25.2.3.1.3.115, Desc : /run/user/4506
   OID : 1.3.6.1.2.1.25.2.3.1.2.115, Storagetype: FixedDisk ?= FixedDisk
   Name : /run/user/4506, Index : 115
OID : 1.3.6.1.2.1.25.2.3.1.3.141, Desc : /run/user/1194
   OID : 1.3.6.1.2.1.25.2.3.1.2.141, Storagetype: FixedDisk ?= FixedDisk
   Name : /run/user/1194, Index : 141
OID : 1.3.6.1.2.1.25.2.3.1.3.61, Desc : /boot
   OID : 1.3.6.1.2.1.25.2.3.1.2.61, Storagetype: FixedDisk ?= FixedDisk
   Name : /boot, Index : 61
OID : 1.3.6.1.2.1.25.2.3.1.3.80, Desc : /run/user/1217
   OID : 1.3.6.1.2.1.25.2.3.1.2.80, Storagetype: FixedDisk ?= FixedDisk
   Name : /run/user/1217, Index : 80
OID : 1.3.6.1.2.1.25.2.3.1.3.7, Desc : Cached memory
   OID : 1.3.6.1.2.1.25.2.3.1.2.7, Storagetype: Other ?= FixedDisk
OID : 1.3.6.1.2.1.25.2.3.1.3.3, Desc : Virtual memory
   OID : 1.3.6.1.2.1.25.2.3.1.2.3, Storagetype: VirtualMemory ?= FixedDisk
OID : 1.3.6.1.2.1.25.2.3.1.3.130, Desc : /run/user/1400
   OID : 1.3.6.1.2.1.25.2.3.1.2.130, Storagetype: FixedDisk ?= FixedDisk
   Name : /run/user/1400, Index : 130
OID : 1.3.6.1.2.1.25.2.3.1.3.10, Desc : Swap space
   OID : 1.3.6.1.2.1.25.2.3.1.2.10, Storagetype: VirtualMemory ?= FixedDisk
OID : 1.3.6.1.2.1.25.2.3.1.3.88, Desc : /run/user/1023
   OID : 1.3.6.1.2.1.25.2.3.1.2.88, Storagetype: FixedDisk ?= FixedDisk
   Name : /run/user/1023, Index : 88
OID : 1.3.6.1.2.1.25.2.3.1.3.152, Desc : /run/user/1287
   OID : 1.3.6.1.2.1.25.2.3.1.2.152, Storagetype: FixedDisk ?= FixedDisk
   Name : /run/user/1287, Index : 152
OID : 1.3.6.1.2.1.25.2.3.1.3.97, Desc : /run/user/4383
   OID : 1.3.6.1.2.1.25.2.3.1.2.97, Storagetype: FixedDisk ?= FixedDisk
   Name : /run/user/4383, Index : 97
OID : 1.3.6.1.2.1.25.2.3.1.3.67, Desc : /run/user/1154
   OID : 1.3.6.1.2.1.25.2.3.1.2.67, Storagetype: FixedDisk ?= FixedDisk
   Name : /run/user/1154, Index : 67
OID : 1.3.6.1.2.1.25.2.3.1.3.151, Desc : /run/user/4056
   OID : 1.3.6.1.2.1.25.2.3.1.2.151, Storagetype: FixedDisk ?= FixedDisk
   Name : /run/user/4056, Index : 151
OID : 1.3.6.1.2.1.25.2.3.1.3.120, Desc : /run/user/61274
   OID : 1.3.6.1.2.1.25.2.3.1.2.120, Storagetype: FixedDisk ?= FixedDisk
   Name : /run/user/61274, Index : 120
OID : 1.3.6.1.2.1.25.2.3.1.3.189, Desc : /run/user/2865
   OID : 1.3.6.1.2.1.25.2.3.1.2.189, Storagetype: FixedDisk ?= FixedDisk
   Name : /run/user/2865, Index : 189
OID : 1.3.6.1.2.1.25.2.3.1.3.70, Desc : /run/user/1396
   OID : 1.3.6.1.2.1.25.2.3.1.2.70, Storagetype: FixedDisk ?= FixedDisk
   Name : /run/user/1396, Index : 70
OID : 1.3.6.1.2.1.25.2.3.1.3.118, Desc : /run/user/65894
   OID : 1.3.6.1.2.1.25.2.3.1.2.118, Storagetype: FixedDisk ?= FixedDisk
   Name : /run/user/65894, Index : 118
OID : 1.3.6.1.2.1.25.2.3.1.3.162, Desc : /run/user/1543
   OID : 1.3.6.1.2.1.25.2.3.1.2.162, Storagetype: FixedDisk ?= FixedDisk
   Name : /run/user/1543, Index : 162
OID : 1.3.6.1.2.1.25.2.3.1.3.196, Desc : /run/user/5972
   OID : 1.3.6.1.2.1.25.2.3.1.2.196, Storagetype: FixedDisk ?= FixedDisk
   Name : /run/user/5972, Index : 196
OID : 1.3.6.1.2.1.25.2.3.1.3.142, Desc : /run/user/1177
   OID : 1.3.6.1.2.1.25.2.3.1.2.142, Storagetype: FixedDisk ?= FixedDisk
   Name : /run/user/1177, Index : 142
OID : 1.3.6.1.2.1.25.2.3.1.3.8, Desc : Shared memory
   OID : 1.3.6.1.2.1.25.2.3.1.2.8, Storagetype: Other ?= FixedDisk
OID : 1.3.6.1.2.1.25.2.3.1.3.75, Desc : /run/user/3070
   OID : 1.3.6.1.2.1.25.2.3.1.2.75, Storagetype: FixedDisk ?= FixedDisk
   Name : /run/user/3070, Index : 75
OID : 1.3.6.1.2.1.25.2.3.1.3.116, Desc : /run/user/1582
   OID : 1.3.6.1.2.1.25.2.3.1.2.116, Storagetype: FixedDisk ?= FixedDisk
   Name : /run/user/1582, Index : 116
OID : 1.3.6.1.2.1.25.2.3.1.3.1, Desc : Physical memory
   OID : 1.3.6.1.2.1.25.2.3.1.2.1, Storagetype: Ram ?= FixedDisk
OID : 1.3.6.1.2.1.25.2.3.1.3.76, Desc : /run/user/3446
   OID : 1.3.6.1.2.1.25.2.3.1.2.76, Storagetype: FixedDisk ?= FixedDisk
   Name : /run/user/3446, Index : 76
OID : 1.3.6.1.2.1.25.2.3.1.3.33, Desc : /var
   OID : 1.3.6.1.2.1.25.2.3.1.2.33, Storagetype: FixedDisk ?= FixedDisk
   Name : /var, Index : 33
OID : 1.3.6.1.2.1.25.2.3.1.3.41, Desc : /run
   OID : 1.3.6.1.2.1.25.2.3.1.2.41, Storagetype: FixedDisk ?= FixedDisk
   Name : /run, Index : 41
OID : 1.3.6.1.2.1.25.2.3.1.3.42, Desc : /sys/fs/cgroup
   OID : 1.3.6.1.2.1.25.2.3.1.2.42, Storagetype: FixedDisk ?= FixedDisk
   Name : /sys/fs/cgroup, Index : 42
OID : 1.3.6.1.2.1.25.2.3.1.3.195, Desc : /run/user/1973
   OID : 1.3.6.1.2.1.25.2.3.1.2.195, Storagetype: FixedDisk ?= FixedDisk
   Name : /run/user/1973, Index : 195
OID : 1.3.6.1.2.1.25.2.3.1.3.122, Desc : /run/user/1737
   OID : 1.3.6.1.2.1.25.2.3.1.2.122, Storagetype: FixedDisk ?= FixedDisk
   Name : /run/user/1737, Index : 122
OID : 1.3.6.1.2.1.25.2.3.1.3.62, Desc : /home
   OID : 1.3.6.1.2.1.25.2.3.1.2.62, Storagetype: FixedDisk ?= FixedDisk
   Name : /home, Index : 62
OID : 1.3.6.1.2.1.25.2.3.1.3.165, Desc : /run/user/2808
   OID : 1.3.6.1.2.1.25.2.3.1.2.165, Storagetype: FixedDisk ?= FixedDisk
   Name : /run/user/2808, Index : 165
OID : 1.3.6.1.2.1.25.2.3.1.3.65, Desc : /run/user/3137
   OID : 1.3.6.1.2.1.25.2.3.1.2.65, Storagetype: FixedDisk ?= FixedDisk
   Name : /run/user/3137, Index : 65
OID : 1.3.6.1.2.1.25.2.3.1.3.193, Desc : /run/user/66540
   OID : 1.3.6.1.2.1.25.2.3.1.2.193, Storagetype: FixedDisk ?= FixedDisk
   Name : /run/user/66540, Index : 193
OID : 1.3.6.1.2.1.25.2.3.1.3.39, Desc : /dev/shm
OID : 1.3.6.1.2.1.25.2.3.1.3.89, Desc : /run/user/1175
   OID : 1.3.6.1.2.1.25.2.3.1.2.89, Storagetype: FixedDisk ?= FixedDisk
   Name : /run/user/1175, Index : 89
OID : 1.3.6.1.2.1.25.2.3.1.3.90, Desc : /run/user/1636
   OID : 1.3.6.1.2.1.25.2.3.1.2.90, Storagetype: FixedDisk ?= FixedDisk
   Name : /run/user/1636, Index : 90
OID : 1.3.6.1.2.1.25.2.3.1.3.174, Desc : /run/user/1688
   OID : 1.3.6.1.2.1.25.2.3.1.2.174, Storagetype: FixedDisk ?= FixedDisk
   Name : /run/user/1688, Index : 174
OID : 1.3.6.1.2.1.25.2.3.1.3.126, Desc : /run/user/2382
   OID : 1.3.6.1.2.1.25.2.3.1.2.126, Storagetype: FixedDisk ?= FixedDisk
   Name : /run/user/2382, Index : 126
OID : 1.3.6.1.2.1.25.2.3.1.3.135, Desc : /run/user/1686
   OID : 1.3.6.1.2.1.25.2.3.1.2.135, Storagetype: FixedDisk ?= FixedDisk
   Name : /run/user/1686, Index : 135
OID : 1.3.6.1.2.1.25.2.3.1.3.66, Desc : /run/user/65362
   OID : 1.3.6.1.2.1.25.2.3.1.2.66, Storagetype: FixedDisk ?= FixedDisk
   Name : /run/user/65362, Index : 66
OID : 1.3.6.1.2.1.25.2.3.1.3.84, Desc : /run/user/1689
   OID : 1.3.6.1.2.1.25.2.3.1.2.84, Storagetype: FixedDisk ?= FixedDisk
   Name : /run/user/1689, Index : 84
OID : 1.3.6.1.2.1.25.2.3.1.3.156, Desc : /run/user/3039
   OID : 1.3.6.1.2.1.25.2.3.1.2.156, Storagetype: FixedDisk ?= FixedDisk
   Name : /run/user/3039, Index : 156
OID : 1.3.6.1.2.1.25.2.3.1.3.129, Desc : /run/user/66236
   OID : 1.3.6.1.2.1.25.2.3.1.2.129, Storagetype: FixedDisk ?= FixedDisk
   Name : /run/user/66236, Index : 129
OID : 1.3.6.1.2.1.25.2.3.1.3.183, Desc : /run/user/3746
   OID : 1.3.6.1.2.1.25.2.3.1.2.183, Storagetype: FixedDisk ?= FixedDisk
   Name : /run/user/3746, Index : 183
OID : 1.3.6.1.2.1.25.2.3.1.3.31, Desc : /
   OID : 1.3.6.1.2.1.25.2.3.1.2.31, Storagetype: FixedDisk ?= FixedDisk
   Name : /, Index : 31
storages selected : 47
Descr : /run/user/1763
Use of uninitialized value in concatenation (.) or string at /app/users/nagios/plugins/check_snmp_storage.pl line 547.
Size :
Use of uninitialized value in concatenation (.) or string at /app/users/nagios/plugins/check_snmp_storage.pl line 548.
Used :
Use of uninitialized value in concatenation (.) or string at /app/users/nagios/plugins/check_snmp_storage.pl line 549.
Alloc :
Data not fully defined for storage /run/user/1763 : UNKNOWN

**Comment by sbraz** [comment]
I'm running into the same issue, it seems to be [a perl bug](https://rt.cpan.org/Public/Bug/Display.html?id=104863).
I added a call to `$session->error()` after https://github.com/dnsmichi/manubulon-snmp/blob/7dbc838af31797840564c51fd21a892fb8d040ce/plugins/check_snmp_storage.pl#L600
and it returns `The message size exceeded the buffer maxMsgSize of 1472`.

When `$result` is `undef`, the plugin should display the return of `error()` as this would be more helpful than `Data not fully defined`.

**Comment by dnsmichi** [comment]
Can you send in a PR please?

**Comment by sbraz** [comment]
@dnsmichi Done, see https://github.com/dnsmichi/manubulon-snmp/pull/45
