### ISSUE TITLE
Nagios shows KB instead of MB with check_snmp_storage

### ISSUE THREAD

**Issue by madmax01** [dnsmichi/manubulon-snmp#38]
Hi there,

once using the script i see that the MB Size is sent to nagios graph. but the graph itself is saying K on the Left.

So Value is 624900.055MB   > but on left is showing it passed the 500KB Line

Could i fix it in the Code somehow? i'am not that familiar with Perl code.

![untitled](https://user-images.githubusercontent.com/5938215/29668489-b2105edc-88e0-11e7-9986-837f7c6c77fa.jpg)

Many thx

Max

**Comment by dnsmichi** [comment]
Sounds like a formatting issue with nagiosgraph - I'd verify the returned performance data units and check your backend and frontend in that tool. Nothing one could fix in the plugin I'm afraid.
