### ISSUE TITLE
check_snmp_int.pl does not allow use of ifName

### ISSUE THREAD

**Issue by turvas** [dnsmichi/manubulon-snmp#42]
Hi,

option "-N" (to use ::ifName to select interface) seems to not exist in current (1.4.6) version, neither in "--help" message, nor in perl file (responds with "unknown option"), but this is needed to select proper interface from Ubuntu 16 (VM under vSphere 6.5, is using for all interfaces ::ifDescr value "VMware VMXNET3 Ethernet Controller").

**Comment by dnsmichi** [comment]
This repository is on 2.1.0 already. Versions before v2.0.0 did not have any feature patches, they were left as the original forked plugins. Ensure to upgrade to the newest version.
