### ISSUE TITLE
Consider Changing check_snmp_load -T netsl value names

### ISSUE THREAD

**Issue by 6d6178** [dnsmichi/manubulon-snmp#55]
After I solved this issue
https://monitoring-portal.org/t/graphite-no-graphs-found/3190
I found that the names of the perfdata, and therefore Graphite are load_1_min.value etc. while the standard load names are load1.value etc..
I want to suggest that the names are changed to the icinga names. Sadly this would be a breaking change which could be resolved with a one-line command but I don't think this is desirable.
I am happy to hear other ideas on how to resolve this or if this is considered to be too minor.

**Comment by dnsmichi** [comment]
There is no standard in perfdata label naming, each plugin may freely decide. You need to adopt your queries/templates against Graphite in this specific way then.

This repository inly incorporates enhancement patches for the original sources, no breaking changes will be introduced, nor any rewrite.

**Comment by 6d6178** [comment]
That's okay then.
Thank you anyway.
