### ISSUE TITLE
check_snmp_load.pl - Linux load multiple CPUs

### ISSUE THREAD

**Issue by dnsmichi** [dnsmichi/manubulon-snmp#6]
Linux load doesn't handle multiple CPUs properly. Here is a patch that makes the plugin to get the number of CPUs for a particular system and multiply warning and critical limits by this number.

**Comment by bsiege** [comment]
Hi Michi,
that breaks snmp-load (for me).
```
"my" variable $resultat masks earlier declaration in same scope at /usr/lib64/nagios/plugins/check_snmp_load.pl line 381.
```
